#!/usr/bin/env bash
# Handle signals and store PID in a file

echo $$ > /tmp/myscript.pid

term_handler() {
    echo "I hate the kill command"
    rm -f /tmp/myscript.pid
    exit
}

int_handler() {
    echo "Y U no love me?!"
}

quit_handler() {
    rm -f /tmp/myscript.pid
    exit
}

trap term_handler SIGTERM
trap int_handler SIGINT
trap quit_handler SIGQUIT

while true; do
    echo "To infinity and beyond"
    sleep 1
done
